server:
  port: 8080

spring:
  application:
    name: pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER_URI:https://login.microsoftonline.com/9cc6bdb0-ec1a-463d-a617-94569680e9ed/v2.0}
          audiences:
            - ${AZURE_AUDIENCE:d240ffb6-49ab-4d31-ac14-5c7bb5e24b3d}

downstream:
  pedidos:
    base-url: ${DOWNSTREAM_PEDIDOS_URL:http://localhost:8081}
  productos:
    base-url: ${DOWNSTREAM_PRODUCTOS_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
